stages:
  - init
  - test
  - build
  - deploy
  - cleanup

variables:
  VENV_ROOT: C:\temp\builds
  VENV_PY35: C:\temp\builds\python35_x64
  WXPYTHON_SNAPSHOTS: https://wxpython.org/Phoenix/snapshot-builds
  PYPI_URL: http://tphweb.tph.local/pypi

# Set environment vars
before_script:
  - REM ==================== Before Script ====================
  # Create the build dir environment variable.
  - set BUILD_DIR=%VENV_PY35%\%CI_PROJECT_ID%
  - set BUILD_DIR=%BUILD_DIR%__%CI_PROJECT_NAMESPACE%
  - set BUILD_DIR=%BUILD_DIR%__%CI_PROJECT_NAME%
  - set BUILD_DIR=%BUILD_DIR%__%CI_PIPELINE_ID%
  - set BUILD_DIR=%BUILD_DIR%__%CI_COMMIT_REF_NAME%
  - echo %BUILD_DIR%

  - call C:\WinPython35\scripts\env.bat
  - python -c "import sys;print(sys.version)"

  - REM ~~~~~~~~~~~~~~~~~~~~ End Before Script ~~~~~~~~~~~~~~~~~~~~

install:
  stage: init
  when: always
  tags:
    - python
  script:
    - python -m venv --clear %BUILD_DIR%
    - call %BUILD_DIR%\Scripts\activate.bat
    # Can't upgrade pip in place.
    # See https://github.com/pypa/pip/issues/1299#issuecomment-188198496
    - python -m pip install --upgrade --no-cache-dir pip
    - python -m pip install --no-cache-dir wheel
    - "python -m pip install --only-binary :all: --pre -f %WXPYTHON_SNAPSHOTS% wxPython_Phoenix"
    - python -m pip install --no-cache-dir -r requirements.txt

test:
  stage: test
  when: on_success
  tags:
    - python
  script:
    - call %BUILD_DIR%\Scripts\activate.bat
    - python -m pip install --no-cache-dir -r dev-requirements.txt
    - python -m green -vvv -s 1 -W -t gdwcalc

build:
  stage: build
  when: on_success
  tags:
    - python
  only:
    - tags
  script:
    - call %BUILD_DIR%\Scripts\activate.bat
#    - python build_exe.py build
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
#      - build/exe.win-amd64-3.5/
      - dist/*

deploy:
  stage: deploy
  environment:
    name: production
    url: $PYPI_URL/simple/gdwcalc
  when: on_success
  tags:
    - python
  only:
    - tags
  script:
    - call C:\WinPython35\scripts\env.bat
    - call %BUILD_DIR%\Scripts\activate.bat
    - python -m pip install --upgrade twine
    - dir dist\*.zip /b/s > temp.txt
    - set /p VAR=<temp.txt
    - echo %VAR%
    - twine register --repository %PYPI_URL% --repository-url %PYPI_URL% -u '' -p '' %VAR%
    - twine upload --repository %PYPI_URL% --repository-url %PYPI_URL% -u '' -p '' dist/*

clean-up:
  stage: cleanup
  when: always
  tags:
    - python
  script:
    - rd /S /Q %BUILD_DIR%
